apply plugin: 'com.android.application'

android {
    namespace 'fi.richie.editions.testapp'

    compileSdk 36

    defaultConfig {
        applicationId "fi.richie.editions.editionstestapp"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    namespace 'fi.richie.editions.testapp'

    lint {
        checkAllWarnings true
        warningsAsErrors true
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation('fi.richie:richiesdk:202602.45') {
        exclude group: 'fi.richie', module: 'booklibraryui'
    }
}
